# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: V:/hardware/m1_for_arty_s7/constraints/m1_for_arty_s7.xdc

# XDC: V:/hardware/m1_for_arty_s7/constraints/m1_for_arty_s7_impl.xdc

# Block Designs: V:/hardware/m1_for_arty_s7/block_diagram/m1_for_arty_s7.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m1_for_arty_s7 || ORIG_REF_NAME==m1_for_arty_s7} -quiet] -quiet

# IP: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_axi_bram_ctrl_0_0/m1_for_arty_s7_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_axi_bram_ctrl_0_0 || ORIG_REF_NAME==m1_for_arty_s7_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_axi_gpio_0_0/m1_for_arty_s7_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_axi_gpio_0_0 || ORIG_REF_NAME==m1_for_arty_s7_axi_gpio_0_0} -quiet] -quiet

# IP: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_axi_gpio_1_0/m1_for_arty_s7_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_axi_gpio_1_0 || ORIG_REF_NAME==m1_for_arty_s7_axi_gpio_1_0} -quiet] -quiet

# IP: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_axi_interconnect_0_0/m1_for_arty_s7_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_axi_interconnect_0_0 || ORIG_REF_NAME==m1_for_arty_s7_axi_interconnect_0_0} -quiet] -quiet

# IP: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_axi_quad_spi_0_0/m1_for_arty_s7_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_axi_quad_spi_0_0 || ORIG_REF_NAME==m1_for_arty_s7_axi_quad_spi_0_0} -quiet] -quiet

# IP: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_axi_uartlite_0_0/m1_for_arty_s7_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_axi_uartlite_0_0 || ORIG_REF_NAME==m1_for_arty_s7_axi_uartlite_0_0} -quiet] -quiet

# IP: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_blk_mem_gen_0_0/m1_for_arty_s7_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_blk_mem_gen_0_0 || ORIG_REF_NAME==m1_for_arty_s7_blk_mem_gen_0_0} -quiet] -quiet

# IP: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_xlconcat_0_0/m1_for_arty_s7_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_xlconcat_0_0 || ORIG_REF_NAME==m1_for_arty_s7_xlconcat_0_0} -quiet] -quiet

# IP: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_xlconcat_1_0/m1_for_arty_s7_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_xlconcat_1_0 || ORIG_REF_NAME==m1_for_arty_s7_xlconcat_1_0} -quiet] -quiet

# IP: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_xlconstant_1_0/m1_for_arty_s7_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_xlconstant_1_0 || ORIG_REF_NAME==m1_for_arty_s7_xlconstant_1_0} -quiet] -quiet

# IP: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_xlconstant_2_0/m1_for_arty_s7_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_xlconstant_2_0 || ORIG_REF_NAME==m1_for_arty_s7_xlconstant_2_0} -quiet] -quiet

# IP: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_CORTEXM1_AXI_0_0/m1_for_arty_s7_CORTEXM1_AXI_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_CORTEXM1_AXI_0_0 || ORIG_REF_NAME==m1_for_arty_s7_CORTEXM1_AXI_0_0} -quiet] -quiet

# IP: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_clk_wiz_0_0/m1_for_arty_s7_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_clk_wiz_0_0 || ORIG_REF_NAME==m1_for_arty_s7_clk_wiz_0_0} -quiet] -quiet

# IP: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_i_const_1_0/m1_for_arty_s7_i_const_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_i_const_1_0 || ORIG_REF_NAME==m1_for_arty_s7_i_const_1_0} -quiet] -quiet

# IP: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_i_interconnect_aresetn_0/m1_for_arty_s7_i_interconnect_aresetn_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_i_interconnect_aresetn_0 || ORIG_REF_NAME==m1_for_arty_s7_i_interconnect_aresetn_0} -quiet] -quiet

# IP: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_i_inv_dbgresetn_0/m1_for_arty_s7_i_inv_dbgresetn_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_i_inv_dbgresetn_0 || ORIG_REF_NAME==m1_for_arty_s7_i_inv_dbgresetn_0} -quiet] -quiet

# IP: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_i_inv_sysresetn1_0/m1_for_arty_s7_i_inv_sysresetn1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_i_inv_sysresetn1_0 || ORIG_REF_NAME==m1_for_arty_s7_i_inv_sysresetn1_0} -quiet] -quiet

# IP: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_i_peripheral_aresetn1_0/m1_for_arty_s7_i_peripheral_aresetn1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_i_peripheral_aresetn1_0 || ORIG_REF_NAME==m1_for_arty_s7_i_peripheral_aresetn1_0} -quiet] -quiet

# IP: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_i_sysresetn_or_0/m1_for_arty_s7_i_sysresetn_or_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_i_sysresetn_or_0 || ORIG_REF_NAME==m1_for_arty_s7_i_sysresetn_or_0} -quiet] -quiet

# IP: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_proc_sys_reset_DAPLink_0/m1_for_arty_s7_proc_sys_reset_DAPLink_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_proc_sys_reset_DAPLink_0 || ORIG_REF_NAME==m1_for_arty_s7_proc_sys_reset_DAPLink_0} -quiet] -quiet

# IP: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_proc_sys_reset_base_0/m1_for_arty_s7_proc_sys_reset_base_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_proc_sys_reset_base_0 || ORIG_REF_NAME==m1_for_arty_s7_proc_sys_reset_base_0} -quiet] -quiet

# IP: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_xbar_0/m1_for_arty_s7_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_xbar_0 || ORIG_REF_NAME==m1_for_arty_s7_xbar_0} -quiet] -quiet

# IP: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_axi_gpio_0_1/m1_for_arty_s7_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_axi_gpio_0_1 || ORIG_REF_NAME==m1_for_arty_s7_axi_gpio_0_1} -quiet] -quiet

# IP: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_axi_interconnect_0_1/m1_for_arty_s7_axi_interconnect_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_axi_interconnect_0_1 || ORIG_REF_NAME==m1_for_arty_s7_axi_interconnect_0_1} -quiet] -quiet

# IP: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_axi_quad_spi_0_1/m1_for_arty_s7_axi_quad_spi_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_axi_quad_spi_0_1 || ORIG_REF_NAME==m1_for_arty_s7_axi_quad_spi_0_1} -quiet] -quiet

# IP: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_axi_single_spi_0_0/m1_for_arty_s7_axi_single_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_axi_single_spi_0_0 || ORIG_REF_NAME==m1_for_arty_s7_axi_single_spi_0_0} -quiet] -quiet

# IP: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_axi_xip_quad_spi_0_0/m1_for_arty_s7_axi_xip_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_axi_xip_quad_spi_0_0 || ORIG_REF_NAME==m1_for_arty_s7_axi_xip_quad_spi_0_0} -quiet] -quiet

# IP: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_DAPLink_to_Arty_shield_0_0/m1_for_arty_s7_DAPLink_to_Arty_shield_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_DAPLink_to_Arty_shield_0_0 || ORIG_REF_NAME==m1_for_arty_s7_DAPLink_to_Arty_shield_0_0} -quiet] -quiet

# IP: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_xbar_1/m1_for_arty_s7_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_xbar_1 || ORIG_REF_NAME==m1_for_arty_s7_xbar_1} -quiet] -quiet

# IP: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_auto_pc_8/m1_for_arty_s7_auto_pc_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_auto_pc_8 || ORIG_REF_NAME==m1_for_arty_s7_auto_pc_8} -quiet] -quiet

# IP: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_auto_pc_7/m1_for_arty_s7_auto_pc_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_auto_pc_7 || ORIG_REF_NAME==m1_for_arty_s7_auto_pc_7} -quiet] -quiet

# IP: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_auto_pc_6/m1_for_arty_s7_auto_pc_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_auto_pc_6 || ORIG_REF_NAME==m1_for_arty_s7_auto_pc_6} -quiet] -quiet

# IP: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_auto_pc_5/m1_for_arty_s7_auto_pc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_auto_pc_5 || ORIG_REF_NAME==m1_for_arty_s7_auto_pc_5} -quiet] -quiet

# IP: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_auto_pc_4/m1_for_arty_s7_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_auto_pc_4 || ORIG_REF_NAME==m1_for_arty_s7_auto_pc_4} -quiet] -quiet

# IP: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_auto_pc_9/m1_for_arty_s7_auto_pc_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_auto_pc_9 || ORIG_REF_NAME==m1_for_arty_s7_auto_pc_9} -quiet] -quiet

# IP: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_auto_pc_3/m1_for_arty_s7_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_auto_pc_3 || ORIG_REF_NAME==m1_for_arty_s7_auto_pc_3} -quiet] -quiet

# IP: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_auto_pc_2/m1_for_arty_s7_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_auto_pc_2 || ORIG_REF_NAME==m1_for_arty_s7_auto_pc_2} -quiet] -quiet

# IP: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_auto_pc_1/m1_for_arty_s7_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_auto_pc_1 || ORIG_REF_NAME==m1_for_arty_s7_auto_pc_1} -quiet] -quiet

# IP: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_auto_pc_0/m1_for_arty_s7_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_auto_pc_0 || ORIG_REF_NAME==m1_for_arty_s7_auto_pc_0} -quiet] -quiet

# XDC: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_axi_bram_ctrl_0_0/m1_for_arty_s7_axi_bram_ctrl_0_0_ooc.xdc

# XDC: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_axi_gpio_0_0/m1_for_arty_s7_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_axi_gpio_0_0 || ORIG_REF_NAME==m1_for_arty_s7_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_axi_gpio_0_0/m1_for_arty_s7_axi_gpio_0_0_ooc.xdc

# XDC: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_axi_gpio_0_0/m1_for_arty_s7_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_axi_gpio_0_0 || ORIG_REF_NAME==m1_for_arty_s7_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_axi_gpio_1_0/m1_for_arty_s7_axi_gpio_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_axi_gpio_1_0 || ORIG_REF_NAME==m1_for_arty_s7_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_axi_gpio_1_0/m1_for_arty_s7_axi_gpio_1_0_ooc.xdc

# XDC: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_axi_gpio_1_0/m1_for_arty_s7_axi_gpio_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_axi_gpio_1_0 || ORIG_REF_NAME==m1_for_arty_s7_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_axi_quad_spi_0_0/m1_for_arty_s7_axi_quad_spi_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_axi_quad_spi_0_0 || ORIG_REF_NAME==m1_for_arty_s7_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_axi_quad_spi_0_0/m1_for_arty_s7_axi_quad_spi_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_axi_quad_spi_0_0 || ORIG_REF_NAME==m1_for_arty_s7_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_axi_quad_spi_0_0/m1_for_arty_s7_axi_quad_spi_0_0_ooc.xdc

# XDC: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_axi_quad_spi_0_0/m1_for_arty_s7_axi_quad_spi_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_axi_quad_spi_0_0 || ORIG_REF_NAME==m1_for_arty_s7_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_axi_uartlite_0_0/m1_for_arty_s7_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_axi_uartlite_0_0 || ORIG_REF_NAME==m1_for_arty_s7_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_axi_uartlite_0_0/m1_for_arty_s7_axi_uartlite_0_0_ooc.xdc

# XDC: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_axi_uartlite_0_0/m1_for_arty_s7_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_axi_uartlite_0_0 || ORIG_REF_NAME==m1_for_arty_s7_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_blk_mem_gen_0_0/m1_for_arty_s7_blk_mem_gen_0_0_ooc.xdc

# XDC: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_CORTEXM1_AXI_0_0/m1_for_arty_s7_CORTEXM1_AXI_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_CORTEXM1_AXI_0_0 || ORIG_REF_NAME==m1_for_arty_s7_CORTEXM1_AXI_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_clk_wiz_0_0/m1_for_arty_s7_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_clk_wiz_0_0 || ORIG_REF_NAME==m1_for_arty_s7_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_clk_wiz_0_0/m1_for_arty_s7_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_clk_wiz_0_0 || ORIG_REF_NAME==m1_for_arty_s7_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_clk_wiz_0_0/m1_for_arty_s7_clk_wiz_0_0_late.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_clk_wiz_0_0 || ORIG_REF_NAME==m1_for_arty_s7_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_clk_wiz_0_0/m1_for_arty_s7_clk_wiz_0_0_ooc.xdc

# XDC: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_proc_sys_reset_DAPLink_0/m1_for_arty_s7_proc_sys_reset_DAPLink_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_proc_sys_reset_DAPLink_0 || ORIG_REF_NAME==m1_for_arty_s7_proc_sys_reset_DAPLink_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_proc_sys_reset_DAPLink_0/m1_for_arty_s7_proc_sys_reset_DAPLink_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_proc_sys_reset_DAPLink_0 || ORIG_REF_NAME==m1_for_arty_s7_proc_sys_reset_DAPLink_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_proc_sys_reset_DAPLink_0/m1_for_arty_s7_proc_sys_reset_DAPLink_0_ooc.xdc

# XDC: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_proc_sys_reset_base_0/m1_for_arty_s7_proc_sys_reset_base_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_proc_sys_reset_base_0 || ORIG_REF_NAME==m1_for_arty_s7_proc_sys_reset_base_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_proc_sys_reset_base_0/m1_for_arty_s7_proc_sys_reset_base_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_proc_sys_reset_base_0 || ORIG_REF_NAME==m1_for_arty_s7_proc_sys_reset_base_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_proc_sys_reset_base_0/m1_for_arty_s7_proc_sys_reset_base_0_ooc.xdc

# XDC: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_xbar_0/m1_for_arty_s7_xbar_0_ooc.xdc

# XDC: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_axi_gpio_0_1/m1_for_arty_s7_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_axi_gpio_0_1 || ORIG_REF_NAME==m1_for_arty_s7_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_axi_gpio_0_1/m1_for_arty_s7_axi_gpio_0_1_ooc.xdc

# XDC: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_axi_gpio_0_1/m1_for_arty_s7_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_axi_gpio_0_1 || ORIG_REF_NAME==m1_for_arty_s7_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_axi_quad_spi_0_1/m1_for_arty_s7_axi_quad_spi_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_axi_quad_spi_0_1 || ORIG_REF_NAME==m1_for_arty_s7_axi_quad_spi_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_axi_quad_spi_0_1/m1_for_arty_s7_axi_quad_spi_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_axi_quad_spi_0_1 || ORIG_REF_NAME==m1_for_arty_s7_axi_quad_spi_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_axi_quad_spi_0_1/m1_for_arty_s7_axi_quad_spi_0_1_ooc.xdc

# XDC: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_axi_quad_spi_0_1/m1_for_arty_s7_axi_quad_spi_0_1_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_axi_quad_spi_0_1 || ORIG_REF_NAME==m1_for_arty_s7_axi_quad_spi_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_axi_single_spi_0_0/m1_for_arty_s7_axi_single_spi_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_axi_single_spi_0_0 || ORIG_REF_NAME==m1_for_arty_s7_axi_single_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_axi_single_spi_0_0/m1_for_arty_s7_axi_single_spi_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_axi_single_spi_0_0 || ORIG_REF_NAME==m1_for_arty_s7_axi_single_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_axi_single_spi_0_0/m1_for_arty_s7_axi_single_spi_0_0_ooc.xdc

# XDC: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_axi_single_spi_0_0/m1_for_arty_s7_axi_single_spi_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_axi_single_spi_0_0 || ORIG_REF_NAME==m1_for_arty_s7_axi_single_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_axi_xip_quad_spi_0_0/m1_for_arty_s7_axi_xip_quad_spi_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_axi_xip_quad_spi_0_0 || ORIG_REF_NAME==m1_for_arty_s7_axi_xip_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_axi_xip_quad_spi_0_0/m1_for_arty_s7_axi_xip_quad_spi_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_axi_xip_quad_spi_0_0 || ORIG_REF_NAME==m1_for_arty_s7_axi_xip_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_axi_xip_quad_spi_0_0/m1_for_arty_s7_axi_xip_quad_spi_0_0_ooc.xdc

# XDC: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_axi_xip_quad_spi_0_0/m1_for_arty_s7_axi_xip_quad_spi_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m1_for_arty_s7_axi_xip_quad_spi_0_0 || ORIG_REF_NAME==m1_for_arty_s7_axi_xip_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_xbar_1/m1_for_arty_s7_xbar_1_ooc.xdc

# XDC: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_auto_pc_8/m1_for_arty_s7_auto_pc_8_ooc.xdc

# XDC: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_auto_pc_7/m1_for_arty_s7_auto_pc_7_ooc.xdc

# XDC: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_auto_pc_6/m1_for_arty_s7_auto_pc_6_ooc.xdc

# XDC: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_auto_pc_5/m1_for_arty_s7_auto_pc_5_ooc.xdc

# XDC: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_auto_pc_4/m1_for_arty_s7_auto_pc_4_ooc.xdc

# XDC: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_auto_pc_9/m1_for_arty_s7_auto_pc_9_ooc.xdc

# XDC: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_auto_pc_3/m1_for_arty_s7_auto_pc_3_ooc.xdc

# XDC: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_auto_pc_2/m1_for_arty_s7_auto_pc_2_ooc.xdc

# XDC: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_auto_pc_1/m1_for_arty_s7_auto_pc_1_ooc.xdc

# XDC: v:/hardware/m1_for_arty_s7/block_diagram/ip/m1_for_arty_s7_auto_pc_0/m1_for_arty_s7_auto_pc_0_ooc.xdc

# XDC: V:/hardware/m1_for_arty_s7/block_diagram/m1_for_arty_s7_ooc.xdc
